/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"level.h"
#include "uart.	h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void) {

	uint8_t value;

	UartInit(9600);
	UartPuts("ADC Demo\r\n");

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // Enable GPIOA

    while (1) {
        uint8_t result = uint8_t DHT_read_sensor(&value);

        if (result == 0) {

            char msg[50];

                // Format the message using sprintf
                sprintf(msg, "Fuel_Level: %d %%\r\n",value);

                // Send the message over UART
                UartPuts(msg);
        }

       delay_us(1000000); // Wait 1 second
    }
}

